name: Build and Test SlotsGameService

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t telecasino-slots .

      - name: Run container in background
        run: |
          docker run -d --name slots -p 8080:8080 telecasino-slots
          sleep 10  # wait for the API to start

      - name: Test API endpoint
        run: |
          curl -v -X POST \
            'http://localhost:8080/api/Slots/play?wager=0.5&gameSessionId=22' \
            -H 'accept: text/plain' \
            -H 'Content-Type: application/json' \
            -d ''

      - name: Test video availability
        run: |
          ID=$(curl -s -X POST \
            'http://localhost:8080/api/Slots/play?wager=1&gameSessionId=22' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '' | jq -r '.id') && \
          curl -s -o /dev/null -w "%{http_code}\n" "http://localhost:8080/${ID}.mp4"

      - name: Show folder tree
        run: |
          docker exec slots tree /shared/Slots

      - name: Stop container
        if: always()
        run: docker stop slots
